---
title: "Ten years of forecast reconciliation"
author: "Rob J Hyndman"
date: ISF 2020
fontsize: 14pt
classoption: aspectratio=169
toc: true
output:
  binb::monash:
    fig_height: 4.33
    fig_width: 7
    colortheme: monashwhite
    keep_tex: no
    includes:
      in_header: header.tex
---







```

```{r selected, fig.width=12, fig.height=6}
energy %>%
  filter(
    Source %in% c('Total', 'Wind', 'Solar', 'Distillate')
  ) %>%
  mutate(
    Source = ordered(Source,
            levels = c('Total','Wind','Solar','Distillate'))
  ) %>%
  ggplot(aes(x=date, y=Generation)) +
  geom_line() +
  facet_wrap(~Source, nrow = 4,  ncol = 1, scales = 'free_y')
```

## Example: Australian electricity generation

\alert{Forecast evaluation}

 * Rolling window of 140 days training data, and one-step-forecasts for 170 days test data.
 * One-layer feed-forward neural network with up to 28 lags of target variable as inputs.
 * Implemented using `NNETAR()` function in `fable` package.
 * Model could be improved with temperature predictor.

## Example: Australian electricity generation

\placefig{0.3}{1.5}{width=7.5cm, height=10cm}{densities}
\begin{textblock}{6}(9,1.7)
\begin{block}{Histogram of residuals:\\ 2 Oct 2019 -- 21 Jan 2020}
Clearly non-Gaussian
\end{block}
\end{textblock}

## Example: Australian electricity generation

\placefig{0.3}{1.5}{width=7.7cm, height=10cm}{corr}

\begin{textblock}{6}(9,1.7)
\begin{block}{Correlations of residuals:\\ 2 Oct 2019 -- 21 Jan 2020}
Blue = positive correlation. Red = negative correlation. Large = stronger correlations.
\end{block}
\end{textblock}

## Example: Australian electricity generation

\placefig{0.3}{1.5}{width=7.2cm, height=10cm}{meanenergyscore}

\begin{textblock}{3.5}(2.5,1.4)\fontsize{12}{12.5}\sf
\begin{block}{}
Mean Energy score
\end{block}
\end{textblock}

\begin{textblock}{7}(8.7,1.3)\fontsize{12}{12.5}\sf
\begin{block}{Base residual assumptions}
\begin{itemize}\itemsep=0cm\parskip=0cm
\item Gaussian independent
\item Gaussian dependent
\item Non-Gaussian independent
\item Non-Gaussian dependent
\end{itemize}
\end{block}\vspace*{-0.1cm}
\begin{block}{Reconciliation methods}
\begin{itemize}\itemsep=0cm\parskip=0cm
\item Base
\item BottomUp
\item BTTH: Ben Taieb, Taylor, Hyndman
\item JPP: Jeon, Panagiotelis, Petropoulos
\item OLS
\item MinT(Shrink)
\item Score Optimal Reconciliation
\end{itemize}
\end{block}
\end{textblock}

## Example: Australian electricity generation

\placefig{0.3}{1.5}{width=6.cm, height=10cm}{nemenyi_ig}

\placefig{8.3}{1.5}{width=6.cm, height=10cm}{nemenyi_jb}

\begin{textblock}{7}(0.2,7.)\fontsize{11}{12}\sf
\begin{block}{Nemenyi test for different scores}
Base forecasts are independent and Gaussian.
\end{block}
\end{textblock}

\begin{textblock}{7}(8.8,7.)\fontsize{11}{12}\sf
\begin{block}{Nemenyi test for different scores}
Base forecasts are obtained by jointly bootstrapping residuals.
\end{block}
\end{textblock}

# Extensions

## Linear combinations

\begin{alertblock}{Optimal linear reconciliation}
\begin{align*}\vspace{-0.3cm}
\bm{y}_t &= \bm{S}\bm{b}_t \\
\tilde{\bm{y}}_{T+h|T} &= \bm{S}(\bm{S}'\bm{W}_h^{-1}\bm{S})^{-1}\bm{S}'\bm{W}_h^{-1} \hat{\bm{y}}_{T+h|T}
\end{align*}
\only<2->{$\bm{S}$ can contain any values, not just 0s and 1s.}
\end{alertblock}

\only<3->{\begin{block}{}
\begin{itemize}
\item Shang, Hyndman (\emph{JCGS}, 2017)
\item Athanasopoulos, Gamakumara, Panagiotelis, Hyndman, Affan (Springer, 2020)
\end{itemize}
\end{block}}

\vspace*{10cm}

## Reconciled linear regression forecasts

If the base forecasts are from a linear regression model, then we can produce coherent forecasts in one step:
\begin{block}{}
\only<1>{\centerline{$\tilde{\bm{y}}_{T+h|T} = \bm{S}(\bm{S}'\bm{\Lambda}_s\bm{S})^{-1}\bm{S}'\bm{\Lambda}_s \hat{\bm{y}}_{T+h|T} \qquad
  \hat{\bm{y}}_{T+h|T} = \bm{X}_{T+h}^* (\bm{X}'\bm{X})^{-1} \bm{X}'\bm{Y}$}}
\only<2->{\centerline{$\tilde{\bm{y}}_{T+h|T} = \bm{S}(\bm{S}'\bm{\Lambda}_s\bm{S})^{-1}\bm{S}'\bm{\Lambda}_s
                            \bm{X}_{T+h}^* (\bm{X}'\bm{X})^{-1} \bm{X}'\bm{Y}$}}
\begin{itemize}\tightlist
\item $\bm{X}$ is matrix of predictors for training set
\item $\bm{X}^*_{T+h}$ is vector of predictors for time $T+h$
\end{itemize}
\end{block}

\only<3->{\begin{block}{}
\centerline{$\bm{V}_h = \sigma^2\bm{S}(\bm{S}'\bm{\Lambda}_s\bm{S})^{-1}\bm{S}'\bm{\Lambda}_s\left[1 + \bm{X}_{T+h}^*(\bm{X}'\bm{X})^{-1}(\bm{X}_{T+h}^*)'\right] \bm{\Lambda}_s\bm{S}'(\bm{S}'\bm{\Lambda}_s\bm{S})^{-1}\bm{S}'$}
\begin{itemize}\tightlist
\item $\sigma^2$ is variance of base model residuals.
\end{itemize}
\end{block}}

\only<4->{\begin{alertblock}{}
Reference: Ashouri, Hyndman, and Shmueli (2019). \url{robjhyndman.com/publications/lhf/}
\end{alertblock}}

\vspace*{10cm}

## Non-negative forecast reconciliation
\fontsize{14}{15}\sf

\begin{block}{Minimum trace (MinT) reconciliation}
The trace of $\bm{V}_h$ is minimized when
$$
  \tilde{\bm{b}}_{T+h|T} = (\bS'\bm{W}_h^{-1}\bS)^{-1}\bS'\bm{W}_h^{-1}\hat{\bm{y}}_{T+h|T}
$$
subject to unbiasedness preservation ($\bS\bG\bS=\bS$).
\end{block}\vspace*{-0.1cm}\pause

Wickramasuriya, Turlach and Hyndman (*S&C*, 2020) replace the unbiased constraint by a non-negative constraint:
$$
  \tilde{\bm{b}}_{T+h|T}\ge0
$$
and show that it can be solved via quadratic programming:

\begin{alertblock}{}
$$
  \text{min}_{\bm{b}} \frac12 \bm{b}'\bS'\bm{W}_h^{-1}\bS\bm{b} - \bm{b}'\bS'\bm{W}_h^{-1}\hat{\bm{y}}_{T+h|T} \quad \text{s.t.~~} \bm{b} \ge 0
$$
\end{alertblock}

## Temporal reconciliation

\only<1>{\begin{tikzpicture}
\tikzstyle{every node}=[ellipse,draw,inner sep=0.2pt,fill=red!15,font=\small]
\tikzstyle[level distance=.1cm]
\tikzstyle[sibling distance=7cm]
\tikzstyle{level 1}=[sibling distance=72mm,set style={{every node}+=[fill=blue!15]}]
\tikzstyle{level 2}=[sibling distance=36mm,set style={{every node}+=[fill=yellow]}]
\tikzstyle{level 3}=[sibling distance=12mm,font=\scriptsize,set style={{every node}+=[fill=green]}]
\node{Annual}[edge from parent fork down]
 child {node {Semi-Annual$_1$}
   child {node {Q$_1$}
     child {node {\scriptsize M$_1$}}
     child {node {\scriptsize M$_2$}}
     child {node {\scriptsize M$_3$}}
   }
   child {node {Q$_2$}
     child {node {\scriptsize M$_4$}}
     child {node {\scriptsize M$_5$}}
     child {node {\scriptsize M$_6$}}
   }
 }
 child {node {Semi-Annual$_2$}
   child {node {Q$_3$}
     child {node {\scriptsize M$_7$}}
     child {node {\scriptsize M$_8$}}
     child {node {\scriptsize M$_9$}}
   }
   child {node {Q$_4$}
     child {node {\scriptsize M$_{10}$}}
     child {node {\scriptsize M$_{11}$}}
     child {node {\scriptsize M$_{12}$}}
   }
 };
\end{tikzpicture}}
\only<2->{\begin{tikzpicture}
\tikzstyle{every node}=[ellipse,draw,inner sep=0.2pt,fill=red!15,font=\small]
\tikzstyle[level distance=.1cm]
\tikzstyle[sibling distance=7cm]
\tikzstyle{level 1}=[sibling distance=48mm,set style={{every node}+=[fill=blue!15]}]
\tikzstyle{level 2}=[sibling distance=24mm,set style={{every node}+=[fill=yellow]}]
\tikzstyle{level 3}=[sibling distance=12mm,set style={{every node}+=[fill=green]}]
\node{Annual}[edge from parent fork down]
 child {node {FourM$_1$}
   child {node {BiM$_1$}
     child {node {\scriptsize M$_1$}}
     child {node {\scriptsize M$_2$}}
   }
   child {node {BiM$_2$}
     child {node {\scriptsize M$_3$}}
     child {node {\scriptsize M$_4$}}
   }
 }
 child {node {FourM$_2$}
   child {node {BiM$_3$}
     child {node {\scriptsize M$_5$}}
     child {node {\scriptsize M$_6$}}
   }
   child {node {BiM$_4$}
     child {node {\scriptsize M$_7$}}
     child {node {\scriptsize M$_8$}}
   }
 }
  child {node {FourM$_3$}
   child {node {BiM$_5$}
     child {node {\scriptsize M$_9$}}
     child {node {\scriptsize M$_{10}$}}
   }
   child {node {BiM$_6$}
     child {node {\scriptsize M$_{11}$}}
     child {node {\scriptsize M$_{12}$}}
   }
 };
\end{tikzpicture}}\pause

\vspace*{10cm}

\only<3>{\begin{textblock}{12}(2,7)
\begin{alertblock}{}
\begin{itemize}
\item[\color{white}\ding{229}] Forecast series at each available frequency.
\item[\color{white}\ding{229}] Optimally combine forecasts within the same year.
\end{itemize}
\end{alertblock}
\end{textblock}}

## Temporal reconciliation
\fontsize{14}{15}\sf

For a time series  $y_1,\dots,y_T$, observed at frequency $m$, we generate aggregate series
\begin{alertblock}{}\vspace*{-0.1cm}
\[
y_j^{\left[k\right]} = \sum^{jk}_{t=1+(j-1)k}{y_t},\qquad \text{for $j = 1,\dots,\lfloor T/k\rfloor$}
\]
\end{alertblock}
* $k \in F(m)=\{\text{factors of $m$}\}$.
* A single unique hierarchy is only possible when there are no coprime pairs in $F(m)$.
* $M_k=m/k$ is seasonal period of aggregated series.
* Proposed by Athanasopoulos, Hyndman, Kourentzes, Petropoulos (*EJOR*, 2017)

## Cross-temporal reconciliation

\begin{block}{}
\begin{itemize}
\item Kourentzes, Athanasopoulos (\emph{ATR}, 2019)
\item Punia, Singh, Madaan (\emph{C\&IE}, 2020)
\item Di Fonzo,  Girolimetto (2020)
\end{itemize}
\end{block}\pause

\begin{alertblock}{ISF talks coming up!}
\begin{itemize}
\item[\ding{229}] Mitch O'Hara-Wild: \emph{Probabilistic cross-temporal hierarchies in fable} (in about 3 hours)
\item[\ding{229}] Tommi Di Fonzo: \emph{Non-negative cross-temporal forecast reconciliation. An application to the Australian domestic tourism flows} (in about 11 hours).
\end{itemize}
\end{alertblock}

\vspace*{10cm}

## Bayesian forecast reconciliation

\large

\begin{block}{}
\begin{itemize}
\item Park, Nassar (\emph{ICML}, 2014)
\item Novak, McGarvie, Garcia (2017)
\item Corani, Azzimonti, Zaffalon (2019)
\item Corani, Azzimonti, Augusto, Zaffalon (2020)
\item Eckert, Hyndman, Panagiotelis (\emph{EJOR}, 2020)
\end{itemize}
\end{block}

## ML and regularization

\large

\begin{block}{}
\begin{itemize}
\item Qiao, Huang (\emph{ICIS}, 2018)
\item Ben Taieb, Koo (\emph{ICKDDM}, 2019)
\item Yang, Hu, Wang (\emph{ICANN}, 2019)
\item Abolghasemi, Hyndman, Tarr, Bergmeir (2019)
\item Spiliotis, Abolghasemi, Hyndman, Petropoulos, Assimakopoulos (2020)
\end{itemize}
\end{block}

## Special IJF issue on hierarchical forecasting

\placefig{0}{1.35}{height=8cm, width=7cm}{IJFcover.jpg}
\begin{textblock}{6.7}(7,1.4)
\begin{block}{Guest Editors}
\begin{itemize}
\item George Athanasopoulos
\item Rob J Hyndman
\item Anastasios Panagiotelis
\item Nikolaos Kourentzes
\end{itemize}
\end{block}\vspace*{0.1cm}
\begin{block}{Call for papers} \url{bit.ly/ijfhierarchical}
\end{block}\vspace*{0.1cm}
\begin{alertblock}{Submission deadline}
31 August 2021
\end{alertblock}
\end{textblock}

## Thanks!

\placefig{0}{1.4}{trim = 10 45 0 0, clip=TRUE, width=10cm, height=2.5cm}{roman}
\placefig{2}{1.4}{trim = 20 20 0 0, clip=TRUE, width=10cm, height=2.7cm}{george}
\placefig{4}{1.4}{trim = 0 10 0 0, clip=TRUE, width=10cm, height=2.5cm}{hanlin}
\placefig{6}{1.4}{trim = 10 0 0 0, clip=TRUE, width=10cm, height=2.5cm}{earowang}
\placefig{8}{1.4}{trim = 0 15 0 0, clip=TRUE, width=10cm, height=2.5cm}{alanlee}
\placefig{10}{1.4}{trim = 30 0 0 0, clip=TRUE, width=10cm, height=2.5cm}{mitch}
\placefig{12}{1.4}{trim = 15 0 0 0, clip=TRUE, width=10cm, height=2.5cm}{shanika}
\placefig{14}{1.4}{trim = 40 0 0 0, clip=TRUE, width=10cm, height=2.5cm}{tas}

\placefig{0}{3.9}{trim = 30 10 30 0, clip=TRUE, width=10cm, height=2.5cm}{puwasala}
\placefig{2}{3.9}{trim = 0 10 0 0, clip=TRUE, width=10cm, height=2.5cm}{fotios}
\placefig{4}{3.9}{trim = 100 30 50 20, clip=TRUE, width=10cm, height=2.5cm}{nikos}
\placefig{6}{3.9}{trim = 50 30 0 0, clip=TRUE, width=10cm, height=2.5cm}{souhaib}
\placefig{8}{3.9}{trim = 110 40 50 0, clip=TRUE, width=10cm, height=2.5cm}{james}
\placefig{10}{3.9}{trim = 40 40 0 0, clip=TRUE, width=10cm, height=2.5cm}{mahdi}
\placefig{12}{3.9}{trim = 50 50 0 0, clip=TRUE, width=10cm, height=2.5cm}{christoph}
\placefig{14}{3.9}{trim = 50 50 0 20, clip=TRUE, width=10cm, height=2.5cm}{fin}

\placefig{0}{6.4}{trim = 10 0 0 0, clip=TRUE, width=10cm, height=2.5cm}{berwin}
\placefig{2}{6.4}{trim = 10 20 0 0, clip=TRUE, width=10cm, height=2.5cm}{galit}
\placefig{4}{6.4}{trim = 10 0 0 0, clip=TRUE, width=10cm, height=2.5cm}{mahsa}
\placefig{6}{6.4}{trim = 10 0 0 0, clip=TRUE, width=10cm, height=2.5cm}{florian}
\placefig{8}{6.4}{trim = 30 0 0 0, clip=TRUE, width=10cm, height=2.5cm}{evan}
\placefig{10}{6.4}{trim = 5 5 0 0, clip=TRUE, width=10cm, height=2.5cm}{vassilis}
\placefig{12}{6.4}{trim = 90 0 0 0, clip=TRUE, width=10cm, height=2.5cm}{carla}
\placefig{14}{6.4}{trim = 0 40 0 0, clip=TRUE, width=10cm, height=2.5cm}{pablo}

## More information
\fontsize{18}{20}\sf

 * Slides and papers: **robjhyndman.com**
 * Packages: **tidyverts.org**
 * Forecasting textbook using fable package: **OTexts.com/fpp3**

\begin{textblock}{8}(7.6,4.8)
\begin{alertblock}{Find me at ...}
\href{https://twitter.com/robjhyndman}{\faicon{twitter} @robjhyndman}

\href{https://github.com/robjhyndman}{\faicon{github}  @robjhyndman}

\href{https://robjhyndman.com}{\faicon{home} robjhyndman.com}

\href{mailto:rob.hyndman@monash.edu}{\faicon{envelope}  rob.hyndman@monash.edu}
\end{alertblock}
\end{textblock}
\vspace*{10cm}